SELECT B.USER_ID, 
        B.NICKNAME, 
        CONCAT(B.CITY, ' ', B.STREET_ADDRESS1, ' ', B.STREET_ADDRESS2) AS 전체주소,
        CONCAT(SUBSTR(B.TLNO, 1, 3), '-', SUBSTR(B.TLNO, 4, 4), '-', SUBSTR(B.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER AS B
WHERE B.USER_ID in (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(WRITER_ID) >= 3)
ORDER BY USER_ID DESC;